routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//  prefix tgat show at url is (adminPnel)
//  prefix tgat show at url is (adminPnel)


//  for language (  package laravel macamara )
Route::group(
[
	'prefix' => LaravelLocalization::setLocale(),
	'middleware' => [ 'localeSessionRedirect', 'localizationRedirect', 'localeViewPath' ]
],
function()
{
	Route::namespace('Front')->name('front.')->group(function()
	{

		Route::get('/','HomeController@index')->name('get.home.index')->middleware('getRoute');
		Route::get('/about','HomeController@about')->name('get.home.about')->middleware('getRoute');

		// contact us page
		Route::get('/contact-us','ContactUsController@contact')->name('get.contactus.contact')->middleware('getRoute');
		// gallery page
		Route::get('/gallery','ContactUsController@gallery')->name('get.contactus.gallery')->middleware('getRoute');

		// portfolio page
		// Route::get('/portfolio','PortfolioController@portfolio')->name('get.portfolio.index')->middleware('getRoute');


		// services 
		Route::get('/services','ServiceController@all')->name('get.service.all')->middleware('getRoute');
		Route::get('/services/search','ServiceController@search')->name('get.service.search')->middleware('getRoute');
		// show services according to category
		Route::get('/service/{slugCat}','ServiceController@category')->name('get.service.category')->middleware('getRoute');
		// show one service
		Route::get('/services/{slugService}','ServiceController@show')->name('get.service.show')->middleware('getRoute');
		// order this service
		Route::post('/services/order','ServiceController@order')->name('post.service.order');





		// products 
		Route::get('/products','ProductsController@all')->name('get.product.all')->middleware('getRoute');
		// show services according to category
		// Route::get('/products/{slugCat}','ProductsController@category')->name('get.product.category')->middleware('getRoute');
		// show one service
		Route::get('/products/{slugProduct}','ProductsController@show')->name('get.product.show')->middleware('getRoute');
		// order this product
		Route::post('/products/order','ProductsController@order')->name('post.product.order');





		// Blog 
		Route::get('/blog','BlogController@index')->name('get.blog.index')->middleware('getRoute');
		Route::get('/blog/search','BlogController@search')->name('get.blog.search')->middleware('getRoute');
		Route::get('/blog/{slugBlog}','BlogController@show')->name('get.blog.show')->middleware('getRoute');



		// subscribe
		Route::post('/subscribe','ContactUsController@subscribe')->name('post.contactus.subscribe');
		// send message from contact us page 
		Route::post('/send-message','ContactUsController@sendMessage')->name('post.contactus.sendMessage');

	});


});

app/Models/Product.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    protected $fillable = ['name','category_id','language_id','img','price','offer',
    'small_description','description','slug','show_in_homePage'];
    public function category()
    {
    	return $this->hasOne('App\Models\Category','id','category_id');
    }


    public function images()
    {
    	return $this->hasMany('App\Models\ServiceImage','service_id','id');
    }
}

app/Http/Controllers/Admin/Product/ImageController.php
<?php

namespace App\Http\Controllers\Admin\Service;

use Illuminate\Http\Request;
use App\Http\Requests\CustomerRequest;
use App\Http\Controllers\Controller;
use App\Models\Service;
use App\Models\ServiceImage ;

use Image;
use Storage;


class ImageController extends Controller
{
   

   // return view of seo data 
    public function addImages($id)
    {
        $data ['service'] = Service::findOrFail($id);
        $data['images'] = ServiceImage::where('service_id',$id)->get();
        return view('admin.service.images.index')->with($data);

    }



     // storing data in db 
    public function moreImages(Request $request)
    {
        $this->validate($request, [

                'id'   => 'required|numeric|exists:services,id',
                'img'   => 'required',
                'img.*' => 'image|mimes:jpeg,png,jpg,gif,svg|max:100000'

        ]);

         if($request->hasfile('img'))
         {
            foreach($request->file('img') as $image)
            { 
                $data = new ServiceImage();

                // upload image using intervention without resizeing
                $img = Image::make($image);
                // save image
                $img->save(UPLOADS_PATH.SERVICE_IMAGES_PATH.$image->hashName());

                $data->service_id = $request->id;
                $data->img = $image->hashName();
                $data->save();

            }
         }
        session()->flash('message',trans('site.added_success'));
        return back();
    }




    public function deleteImage($id)
    {
        $data = ServiceImage::findOrFail($id);
        Storage::disk('public_uploads')->delete(SERVICE_IMAGES_PATH.$data->img);
        ServiceImage::destroy($id);
        session()->flash('message',trans('site.deleted_success'));
        return back();


    }








}

app/Http/Controllers/Admin/ProductController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Requests\ProductRequest;
use App\Http\Controllers\Controller;
use App\Models\Product;
use App\Models\Category;


use Image;
use Storage;
use App\Helpers\Classes\UploadClass;

class ProductController extends Controller
{



    public function index()
    {
    	$data['product'] = Product::select('id','name','language_id','status','sort','category_id','price')
    	->where('language_id',language())
    	->orderBy('sort')
    	->paginate(30);
    	return view('admin.product.index')->with($data);
    }



    // return view of adding data 
    public function add()
    {
        $data['categories'] = Category::select('id','name','language_id')
        ->where('language_id',adminAuth()->user()->language_id)
        ->orderBy('sort')
        ->get();
    	return view('admin.product.add')->with($data);
    }





    // storing data in db 
    public function store(ProductRequest $request)
    {
    	$data = $request->validated();
    	$data['language_id'] = language();

        // upload image of this module
        if($request->hasFile('img'))
        {
            // UPLOADS_PATH.CATEGORY_PATH 
            // -> static path ( you can change it from helpers/files/basehelper)
            $img = UploadClass::uploadImage($request,'img',UPLOADS_PATH.PRODUCT_PATH,178,600,205,500);
            $data['img'] = $img;
        }
        //  slug
        if($request->slug != ''){$data['slug'] = str_slug($request->slug);}
        else{$data['slug'] = str_slug   ($request->name).uniqid();}
    	Product::create($data); // inserting data 
    	session()->flash('message',trans('site.added_success'));
    	return redirect(route('admin.get.product.index'));
    }







    // return view of editing data 
    public function edit($id)
    {
        $data['categories'] = Category::select('id','name','language_id')
        ->where('language_id',adminAuth()->user()->language_id)
        ->orderBy('sort')
        ->get();
    	$data['row'] = Product::findOrFail($id);
    	return view('admin.product.edit')->with($data);
    }



    // storing data in db 
    public function update(ProductRequest $request)
    {
    	$data = $request->validated();

        // upload image of this module
        if($request->hasFile('img'))
        {
            $old = Product::findOrFail($request->id);
            // delete old image from server
            if($old->img)
            {
                Storage::disk('public_uploads')->delete(PRODUCT_PATH.$old->img);
                Storage::disk('public_uploads')->delete(PRODUCT_PATH.'small/'.$old->img);
                Storage::disk('public_uploads')->delete(PRODUCT_PATH.'medium/'.$old->img);
            }
            // UPLOADS_PATH.CATEGORY_PATH 
            // -> static path ( you can change it from helpers/files/basehelper)
            $img = UploadClass::uploadImage($request,'img',UPLOADS_PATH.PRODUCT_PATH,178,600,205,500);
            $data['img'] = $img;
        }
        //  slug
        if($request->slug != ''){$data['slug'] = str_slug($request->slug);}
        else{$data['slug'] = str_slug($request->name).uniqid();}
    	// updating data in db
    	Product::where('id', $request->id)->update($data);
    	session()->flash('message',trans('site.updated_success'));
    	return redirect(route('admin.get.product.index'));
    }



















    // deleteing row from db  ( soft delete )
    public function delete($id)
    {

    	$old = Product::findOrFail($id);

        Storage::disk('public_uploads')->delete(PRODUCT_PATH.$old->img);
        Storage::disk('public_uploads')->delete(PRODUCT_PATH.'small/'.$old->img);
        Storage::disk('public_uploads')->delete(PRODUCT_PATH.'medium/'.$old->img);


    	Product::findOrFail($id)->delete();
    	session()->flash('message',trans('site.deleted_success'));
    	return back();

    }

    // delete mutli row from table 
    public function deleteMulti(Request $request)
    {
    	foreach ($request->deleteMulti as  $value) 
    	{

            $old = Product::findOrFail($value);
            Storage::disk('public_uploads')->delete(PRODUCT_PATH.$old->img);
            Storage::disk('public_uploads')->delete(PRODUCT_PATH.'small/'.$old->img);
            Storage::disk('public_uploads')->delete(PRODUCT_PATH.'medium/'.$old->img);
    		Product::findOrFail($value)->delete();
	    	
    	}

    	session()->flash('message',trans('site.deleted_success'));
	    return back();
    }


     // delete mutli row from table 
    public function sort(Request $request)
    {
    	$i = 1;
    	foreach ($request->sort as  $value) 
    	{
    		$data = Product::find($value);
    		$data->sort = $i;
    		$data->save();
    		$i++;
    	}
    	session()->flash('message',trans('site.sorted_success'));
	    return back();
    }






    // visibility  for this item ( active or not active  -- change status of this item )
    public function visibility($id)
    {
    	$data = Product::findOrFail($id);

    	switch ($data->status) 
    	{
    		case 'yes':
    			$data->status = 'no';
    			$data->save();
    			session()->flash('message',trans('site.deactivate_message'));
    			break;

    		case 'no':
    			$data->status = 'yes';
    			session()->flash('message',trans('site.activate_message'));
    			$data->save();
    			break;
    		
    		default:
    			# code...
    			break;
    	}

    	return back();

    }















   // return view of seo data 
    public function seo($id)
    {
        $data['seo'] = Product::where('language_id',language())->findOrFail($id);
        $data['seoData'] = json_decode($data['seo']['seo']);
        return view('admin.product.seo')->with($data);

    }



     // storing data in db 
    public function updateSeo(Request $request)
    {
        $data = $request->except('id','_token');
        // updating data in db
        $seoData = Product::find($request->id);
        $seoData->seo = json_encode($data);
        $seoData->save();
        session()->flash('message',trans('site.updated_success'));
        return back();
    }











}

app/Http/Controllers/Front/BlogController.php
<?php

namespace App\Http\Controllers\Front;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

use App\Models\Category;
use App\Models\Blog;


class BlogController extends Controller
{
    
    //
    public function index()
    {
        $data['posts'] = Blog::select('name','slug','small_description','img','created_at')
        ->where('status','yes')
        ->where('language_id',lang_front())->paginate(15);

        $data['latest'] = Blog::select('name','slug')
        ->where('language_id',lang_front())->latest()->take(15)->get();

        return view('front.blog.index')->with($data);
    }



    //
    public function search(Request $request)
    {   

        if($request->search && $request->search != '')
        {
            $data['posts'] = Blog::select('name','slug','small_description','img','created_at')
            ->where('status','yes')
            ->where('tags','Like','%'.$request->search.'%')
            ->orWhere('name','Like','%'.$request->search.'%')
            ->orWhere('small_description','Like','%'.$request->search.'%')
            ->orWhere('description','Like','%'.$request->search.'%')
            ->where('language_id',lang_front())->paginate(15);
        }
        else
        {
            $data['posts'] = Blog::select('name','slug','small_description','img','created_at')
            ->where('status','yes')
            ->where('language_id',lang_front())->paginate(15);
        }

        

        $data['latest'] = Blog::select('name','slug','created_at')
        ->where('language_id',lang_front())->latest()->take(6)->get();

        return view('front.blog.index')->with($data);
    }




    // view data of specific blog 
    public function show($slugBlog)
    {
        $check = Blog::where('language_id',lang_front())
        ->where('status','yes')->where('slug',$slugBlog)->first();
        if($check)
        {
            $data['latest'] = Blog::select('name','slug')->where('status','yes')
            ->where('language_id',lang_front())->latest()->take(6)->get();
            $data['row'] = $check;

            $data['posts'] = Blog::select('name','slug','created_at')
            ->where('status','yes')
            ->where('language_id',lang_front())->take(4)->latest()->get();



            return view('front.blog.show')->with($data);
        }
    }

}

app/Http/Controllers/Front/ContactUsController.php
<?php

namespace App\Http\Controllers\Front;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

use App\Models\Newsletter;
use App\Models\Message;


use App\Models\Category;
use App\Models\Brand;
use App\Models\SubCategory;


class ContactUsController extends Controller
{
    


    public function contact()
    {
    	return view('front.static.contact');
    }


    // send message   
    public function sendMessage(Request $request)
    {
        // dd("zfvdvd");

        if($request->ajax())
        {

            $request->validate([

                'name' => 'required|string|max:100',
                'phone' => 'required|numeric|digits_between:6,15',
                'email' => 'required|email|max:100',
                'message' => 'required|string|max:2000',
            ]);

            $data = $request->except("_token");

            Message::create($data);
            $message['success'] = trans('frontSite.contactusMessage');
            return response()->json($message);
        }
    }





    //  gallery
    public function gallery()
    {
    	return view('front.static.gallery');
    }




    public function subscribe(Request $request)
    {

        $request->validate(['email'=> 'required|email|unique:newsletters,email']);
        $data = new Newsletter();
        $data->email = $request->email;
        $data->save();
        $message['success'] = trans('frontSite.subscribeMessage');
        return response()->json($message);

    }






}

app/Http/Controllers/Front/HomeController.php
<?php

namespace App\Http\Controllers\Front;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

use App\Models\Slider;
use App\Models\Product;
use App\Models\Category;
use App\Models\Testimonial;
use App\Models\Team;


class HomeController extends Controller
{
    
    // base function for admin 
    public function index()
    {
        $data['slider'] = Slider::select('name','description','img','link')
        ->where('status','yes')
        ->where('language_id',lang_front())->take(3)->get();

        // Products
        $data['products'] = Product::select('name','category_id','img','slug','price')
        ->where('language_id',lang_front())
        ->where('status','yes')
        ->where('show_in_homePage','yes')->take(8)->get();


        $data['testi'] = Testimonial::select('name','desc','img','position')
        ->where('status','yes')
        ->where('language_id',lang_front())->take(5)->get();

        $data['team'] = Team::select('name','desc','img','position','facebook','twitter','instagram','linkedin')
        ->where('status','yes')
        ->where('language_id',lang_front())->take(4)->get();


        
        return view('front.index')->with($data);
    }



    // base function for admin 
    public function about()
    {

        $data['team'] = Team::select('name','desc','img','position','facebook','twitter','instagram','linkedin')
        ->where('status','yes')
        ->where('language_id',lang_front())->take(4)->get();
        
        return view('front.static.about')->with($data);
    }

}

resources/views/front/products/index.blade.php
@extends('front.main')


@section('content')



    <!-- Start: Breadcrumb Area
    ============================= -->

    <section id="breadcrumb-area">
        <div class="container">
            <div class="row">
                <div class="col-12 text-center">
                    <h2>Products</h2>
                    <ul class="breadcrumb-nav list-inline">
                        <li><a href="{{ route('front.get.home.index') }}">Home</a></li>
                        <li>Products</li>
                    </ul>
                </div>
            </div>
        </div>
    </section>

    <!-- End: Breadcrumb Area
    ============================= -->





      <!-- Start: Pricing
    ============================= -->
    
    <section id="portfolio" class="section-padding pricing-page">
        <div class="container">
            <div class="row">
                <div class="col-lg-6 offset-lg-3 col-12 text-center">
                    <div class="section-title">
                        <h2>Pricing</h2>
                        <hr>
                        <p>You can judge my work by the portfolio we have done</p>
                    </div>
                </div>
            </div>

            <div class="row">
                <div class="col-lg-12">
             
                    <div class="tab-content">
                       
                        <div id="massage" class="tab-pane fade-in active">
                            <ul>
                                @foreach($allProducts as $prod)
                                <li>
                                    <a href="{{route('front.get.product.show',[$prod->slug])}}">
                                    <img src="{{getImage(PRODUCT_PATH.'small/'.$prod->img)}}" alt="{{$prod->name}}">
                                    </a>
                                    <a href="{{route('front.get.product.show',[$prod->slug])}}"><h4>{{$prod->name}} <span class="price">${{$prod->price}}</span></h4></a>
                                    <p>{{\Str::Words($prod->small_description,'6','...')}}</p>
                                </li>
                                @endforeach
                          
                            </ul>
                        </div>
                 
                    </div>
                </div>
            </div>

            
        </div>
    </section>

    <!-- End: Pricing
    ============================= -->



@endsection

resources/views/front/products/show.blade.php
@extends('front.main')


@section('content')


 <!-- Start: Our Pricing Plan
    ============================= -->
    
    <section id="pricing" class="section-padding">
        <div class="container">
            <div class="row">
                <div class="col-lg-6 offset-lg-3 col-12 text-center">
                 
                </div>
            </div>

            <div class="row">
                
                <div class="col-lg-12">
                    <div class="pricing-box text-center" style="background: url({{furl()}}/img/pricing/pricing01.jpg) no-repeat center / cover; border:2px solid #222;">
                        <h3>{{$row->name}}</h3>
                        <hr>
                        <h3>  <img src="{{getImage(PRODUCT_PATH.'small/'.$row->img)}}" class="img-thumbnail"> </h3>
                        <hr>
                        
                        <div class="price"><sup>$</sup> <span>{{$row->price}}</span></div>
                        <ul class="pricing-content">
                            <p>
                            	{!!$row->description!!}
                            </p>
                        </ul>
                        
                    </div>
                </div>
            </div>
        </div>
    </section>

    <!-- End: Our Pricing Plan
    ============================= -->



        <!-- Start: Appoinment
    ============================= -->
    
    <section id="appoinment" class="section-padding">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="opening-hours">
                        <h3>Opening Hours</h3>
                        <p>A collection of textile samples lay spread out on the table Samsa was a travelling salesman.</p>
                        <ul>
                            <li>Monday :    8:00am - 21:00pm</li>
                            <li>Monday :    8:00am - 21:00pm</li>
                            <li>Monday :    8:00am - 21:00pm</li>
                            <li>Monday :    8:00am - 21:00pm</li>
                            <li>Sunday:     Close</li>
                        </ul>
                    </div>
                    <div class="appoinment-wrapper">
                        <form  id="order-form">
                            <div class="">
		                        <h3>Ask For This Product</h3>
		                        <br>
		                        <br>
		                    </div>

                            @csrf
                            <div class="col-md-12">
                                <ul id="errors"></ul>
                                <input type="hidden" name="product_id" value="{{$row->id}}">
                                
                            </div>
                            <span class="input input--hantus">
                                <input required placeholder="Name" class="input__field input__field--hantus" type="text" id="input-08" name="name" />
                              
                            </span>


                            <span class="input input--hantus">
                                <input required placeholder="Email" name="email" class="input__field input__field--hantus" type="email" id="input-011"  />
                         
                            </span>


                            <span class="input input--hantus">
                                <input placeholder="Phone" name="phone" class="input__field input__field--hantus" type="number" id="input-09"  />
                          
                            </span>
        
                            <span class="input input--hantus textarea">
                                <textarea required   placeholder="Message" name="message" class="input__field input__field--hantus" rows="5" id="input-10"></textarea>
                            
                            </span>

                            <button type="submit" class="boxed-btn">@lang('frontSite.submit')</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <!-- End: Appoinment
    ============================= -->

@endsection


@section('script')

<script type="text/javascript">
    $('#order-form').parsley();
</script>
<script type="text/javascript">
  


    $.ajaxSetup({
        headers: {'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')}
    });

   

    $("#order-form").submit(function(e) 
    {
        e.preventDefault();

        // return false;
        var formData  = new FormData(jQuery('#order-form')[0]);
        $.ajax({

           type:'POST',
           url:"{{route('front.post.product.order')}}",
           data:formData,
           contentType: false,
           processData: false,
           success:function(data)
           {
             $("#errors").html('');
             $("#errors").append("<li class='alert alert-success text-center'>"+data.success+"</li>")
             $('.input--hantus').find("input,textarea").val("");
           },
            error: function(xhr, status, error) 
            {
              $("#errors").html('');
              $.each(xhr.responseJSON.errors, function (key, item) 
              {
                $("#errors").append("<li class='alert alert-danger show-errors'>"+item+"</li>")
              });
            }

        });

	});

</script>



@endsection